version: "3"

services:
  agent:
    build:
      context: ./agent
    volumes: 
      - ./agent:/app
    networks:
        - default

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web/www/nginx/conf.d/:/etc/nginx/conf.d/
      - ./web/www:/var/www/
    networks:
        - default



  app:
    build:
      context: ./web/www
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes: 
      - ./web/www:/var/www/
    networks:
        - default
  mysql:
    image: mysql:8.0.18
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_DATABASE: data
    volumes:
        - ./data/mysql:/var/lib/mysql
    networks:
        - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - redis
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8081:80'
    volumes: 
      - /sessions
    networks:
        - default

  redis:
    image: redis
    command: redis-server --requirepass 1234
    environment:
    - ALLOW_EMPTY_PASSWORD=yes
    - REDIS_PASSWORD=1234
    networks:
        - default


     


networks:
  default:
    driver: bridge